
local MP = minetest.get_modpath("rangedweapons")

dofile(MP.."/ration.lua")                                                                                                                                           dofile(MP.."/medkit.lua")                                                                                                                                                dofile(MP.."/sandbag.lua")                                                                                                                                   dofile(MP.."/barbedwire.lua")                                                                                                                                            dofile(MP.."/kenkaren.lua")                                                                                                                                    dofile(MP.."/dontreadonme.lua")                                                                                                                                         dofile(MP.."/kenosha.lua")                                                                                                                                            dofile(MP.."/spam.lua")                                                                                                                                                 dofile(MP.."/tuna.lua")    
dofile(MP.."/incendiary.lua") 
dofile(MP.."/fueltank.lua")  
dofile(MP.."/nailmag.lua")    
dofile(MP.."/tazerbullet.lua") 
dofile(MP.."/new_shelling.lua")
dofile(MP.."/bfg_ammo.lua")
dofile(MP.."/mlgbullets.lua")    
dofile(MP.."/lavammo.lua")
dofile(MP.."/frogweapons.lua")
dofile(MP.."/plasmammo.lua")
dofile(MP.."/demammo.lua")
dofile(MP.."/gastank.lua")
dofile(MP.."/pipebomb.lua")
dofile(MP.."/stickbomb.lua")
dofile(MP.."/fragrenade.lua")
dofile(MP.."/placeablebombs.lua")
dofile(MP.."/bomb.lua")
dofile(MP.."/holybomb.lua")
dofile(MP.."/dynamite.lua")
dofile(MP.."/handgrenade2.lua")

                                                                                                                         
