
local MP = minetest.get_modpath("rangedweapons")

dofile(MP.."/ration.lua")                                                                                                                                           dofile(MP.."/medkit.lua")                                                                                                                                                dofile(MP.."/sandbag.lua")                                                                                                                                           dofile(MP.."/camouflage.lua")                                                                                                                                dofile(MP.."/barbedwire.lua")                                                                                                                                  dofile(MP.."/chainlink.lua")                                                                                                                                             dofile(MP.."/kenkaren.lua")                                                                                                                                    dofile(MP.."/dontreadonme.lua")                                                                                                                                         dofile(MP.."/kenosha.lua")                                                                                                                                            dofile(MP.."/spam.lua")                                                                                                                                                 dofile(MP.."/tuna.lua")    
dofile(MP.."/incendiary.lua") 
dofile(MP.."/fueltank.lua")  
dofile(MP.."/nailmag.lua")    
dofile(MP.."/tazerbullet.lua") 
dofile(MP.."/new_shelling.lua")                                                                                                                              
